version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/electric-sqlite"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/electric-pglite"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/local-sqlite3"
    schedule:
      interval: "weekly"
