name: electric

configs:
  postgres_config:
    file: "./electricsql-postgres.conf"

volumes:
  pg_data:

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db_password
    command:
      - -c
      - config_file=/etc/postgresql.conf
    configs:
      - source: postgres_config
        target: /etc/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 3s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  electric:
    container_name: electric
    hostname: electric
    image: electricsql/electric:canary
    init: true
    environment:
      ELECTRIC_WRITE_TO_PG_MODE: direct_writes
      DATABASE_URL: postgresql://postgres:db_password@postgres:5432/electric
      LOGICAL_PUBLISHER_HOST: electric
      PG_PROXY_PASSWORD: proxy_password
      AUTH_MODE: insecure
      LOG_LEVEL: debug
    ports:
      - 5133:5133
      - 65432:65432
    healthcheck:
      test: ["CMD-SHELL", "return", "0"]
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 3s
    depends_on:
      postgres:
        condition: service_healthy
