name: active-active

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  active-active:
    uses: nurturenature/jepsen-causal-consistency/.github/workflows/run-jepsen-tests.yml@main
    with:
      workloads: >
        [ 'active-active' ]
      nemeses: >
        [ 'none' ]
      rates: >
        [ '10', '20', '30' ]
      time-limits: >
        ['60', '180', '300' ]
      cli-opts: >
        '--postgres-nodes n1,n2'
