name: 'better-sqlite3'

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  better-sqlite:
    uses: nurturenature/jepsen-causal-consistency/.github/workflows/run-jepsen-tests.yml@main
    with:
      workloads: >
        [ 'better-sqlite' ]
      nemeses: >
        [ 'none' ]
      rates: >
        [ '10' ]
      time-limits: >
        ['60' ]
