name: 'SQLite3 + better-sqlite3 API + Multi Transactions'

on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Name of Test'
        type: string
        required: true
        default: 'SQLite3 + better-sqlite3 API + Multi Transactions'
      jepsen_cli:
        description: 'Jepsen CLI'
        type: string
        required: true
        default: 'lein run test --workload better-sqlite --rate 10 --time-limit 60'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  electric-sqlite-multi-txn:
    uses: nurturenature/jepsen-causal-consistency/.github/workflows/ad-hoc-jepsen-test.yml@main
    with:
      test_name: ${{ inputs.test_name || 'SQLite3 + better-sqlite3 API + Multi Transactions' }}
      jepsen_cli: ${{ inputs.jepsen_cli || 'lein run test --workload better-sqlite --rate 10 --time-limit 60' }}
