name: electric-sqlite Going Offline and Online

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  electric-sqlite-offline-online:
    uses: nurturenature/jepsen-causal-consistency/.github/workflows/run-jepsen-tests.yml@main
    with:
      workloads: >
        [ 'electric-sqlite-strong' ]
      nemeses: >
        [ 'offline-online' ]
      rates: >
        [ '10' ]
      time-limits: >
        ['100' ]
