name: 'ElectricSQL: Low tps for 30 Minutes'

on:
  workflow_dispatch:
    inputs:
      jepsen_cli:
        description: 'Low tps for 30 Minutes'
        type: string
        required: true
        default: 'lein run test --workload lww-strong --rate 1 --time-limit 1800'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  electricsql-low-tps-for-30-minutes:
    uses: nurturenature/jepsen-causal-consistency/.github/workflows/ad-hoc-jepsen-test.yml@main
    with:
      jepsen_cli: ${{ inputs.jepsen_cli || 'lein run test --workload lww-strong --rate 1 --time-limit 1800' }}

