name: 'ElectricSQL: Low tps for 30 Minutes'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

env:
  jepsen_cli: 'lein run test --workload lww-strong --rate 1 --time-limit 1800'

jobs:
  electricsql-low-tps-for-30-minutes:
    runs-on: ubuntu-latest

    steps:
      - name: ${{ env.jepsen_cli }}
        uses: nurturenature/jepsen-causal-consistency/.github/workflows/ad-hoc-jepsen-test.yml@main
        with:
          jepsen_cli: ${{ env.jepsen_cli }}
