name: 'SQLite3 + Generated API Time and Rate-Limit Matrix'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  electric-sqlite-single-txn-rate-time-limit-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rate: [10 50 100]
        time-limit: [60 300 600 3600]
    steps:
      - uses: ./.github/workflows/ad-hoc-jepsen-test.yml@main
        with:
          test_name: SQLite3 + Generated API at ${{ matrix.rate }}tps for ${{ matrix.time-limit }}s
          jepsen_cli: lein run test --workload electric-sqlite-strong --rate ${{ matrix.rate }} --time-limit ${{ matrix.time-limit }}

