name: pgexec-pglite

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  pgexec-pglite:
    uses: nurturenature/jepsen-causal-consistency/.github/workflows/run-jepsen-tests.yml@main
    with:
      workloads: >
        [ 'pgexec-pglite' ]
      nemeses: >
        [ 'none' ]
      rates: >
        [ '10' ]
      time-limits: >
        ['60' ]
