name: Run Jepsen Tests

on:
  workflow_dispatch:
    inputs:
      workloads:
        description: 'Workloads (as JSON)'
        type: string
        required: true
        default: '[ electric-sqlite ]'
      nemeses:
        description: 'Nemeses (as JSON)'
        type: string
        required: true
        default: '[ none ]'
      rates:
        description: 'Rates (as JSON)'
        type: string
        required: true
        default: '[ 10 ]'
      time-limits:
        description: 'Timelimits (as JSON)'
        type: string
        required: true
        default: '[ 60 ]'

  workflow_call:
    inputs:
      workloads:
        description: 'Workloads (as JSON)'
        type: string
        required: true
        default: '[ electric-sqlite ]'
      nemeses:
        description: 'Nemeses (as JSON)'
        type: string
        required: true
        default: '[ none ]'
      rates:
        description: 'Rates (as JSON)'
        type: string
        required: true
        default: '[ 10 ]'
      time-limits:
        description: 'Timelimits (as JSON)'
        type: string
        required: true
        default: '[ 60 ]'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workload:   ${{ fromJSON(inputs.workloads) }}
        nemesis:    ${{ fromJSON(inputs.nemeses) }}
        rate:       ${{ fromJSON(inputs.rates) }}
        time-limit: ${{ fromJSON(inputs.time-limits) }}

    env:
      test-title: ${{ matrix.workload }}-${{ matrix.nemesis }}-${{ matrix.rate }}tps-${{ matrix.time-limit }}s

    steps:  
      - name: Checkout jepsen-causal-consistency
        uses: actions/checkout@v4
        
      - name: Bring Up Docker Environment
        run: |
          cd $GITHUB_WORKSPACE/docker
          ./electricsql-build.sh
          ./electricsql-up.sh
          docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}'
          
      - name: ${{ env.test-title }}
        run: |
          cd $GITHUB_WORKSPACE/docker
          ./electricsql-run-migrations.sh
          ./jepsen-docker-cli.sh lein run test --workload   ${{ matrix.workload }} \
                                               --nemesis    ${{ matrix.nemesis }}  \
                                               --rate       ${{ matrix.rate }}     \
                                               --time-limit ${{ matrix.time-limit }}

      - name: Jepsen, ElectricSQL, and PostgreSQL Logs
        if: ${{ always() }}
        run: |
          docker cp jepsen-control:/jepsen/jepsen-causal-consistency/store $GITHUB_WORKSPACE
          docker logs jepsen-electric-1 > $GITHUB_WORKSPACE/store/current/electricsql.log 
          docker logs jepsen-postgres-1 > $GITHUB_WORKSPACE/store/current/postgresql.log 
          
      - name: 'Jepsen Test Artifacts: results'
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.test-title }}-results'
          path: |
            ${{ github.workspace }}/store/current/results.edn
            
      - name: 'Jepsen Test Artifacts: full'
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.test-title }}-full'
          path: |
            ${{ github.workspace }}/store/current
