name: Run Jepsen Tests

on:
  workflow_dispatch:
    inputs:
      workloads:
        description: Workloads (as JSON)
        type: string
        required: true
        default: "[ 'electric-sqlite' ]"
      nemeses:
        description: 'Nemeses (as JSON)'
        type: string
        required: true
        default: "[ 'none' ]"
      rates:
        description: 'Rates (as JSON)'
        type: string
        required: true
        default: "[ '10' ]"
      time-limits:
        description: 'Timelimits (as JSON)'
        type: string
        required: true
        default: "[ '60' ]"
      cli-opts:
        description: 'CLI opts string'
        type: string
        required: false
       
  workflow_call:
    inputs:
      workloads:
        description: 'Workloads (as JSON)'
        type: string
        required: true
        default: "[ 'electric-sqlite' ]"
      nemeses:
        description: 'Nemeses (as JSON)'
        type: string
        required: true
        default: "[ 'none' ]"
      rates:
        description: 'Rates (as JSON)'
        type: string
        required: true
        default: "[ '10' ]"
      time-limits:
        description: 'Timelimits (as JSON)'
        type: string
        required: true
        default: "[ '60' ]"
      cli-opts:
        description: 'CLI opts string'
        type: string
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workload:   ${{ fromJSON(inputs.workloads) }}
        nemesis:    ${{ fromJSON(inputs.nemeses) }}
        rate:       ${{ fromJSON(inputs.rates) }}
        time-limit: ${{ fromJSON(inputs.time-limits) }}

    env:
      test-title: ${{ matrix.workload }}-${{ matrix.nemesis }}-${{ matrix.rate }}tps-${{ matrix.time-limit }}s

    steps:  
      - name: Checkout jepsen-causal-consistency
        uses: actions/checkout@v4
        
      - name: Bring Up Docker Environment
        run: |
          cd $GITHUB_WORKSPACE/docker
          ./electricsql-build.sh
          ./electricsql-up.sh
          
      - name: ${{ env.test-title }}
        run: |
          cd $GITHUB_WORKSPACE/docker
          ./jepsen-docker-cli.sh lein run test --workload   ${{ matrix.workload }} \
                                               --nemesis    ${{ matrix.nemesis }}  \
                                               --rate       ${{ matrix.rate }}     \
                                               --time-limit ${{ matrix.time-limit }} \
                                               ${{ inputs.cli-opts }}

      - name: Jepsen, ElectricSQL, and PostgreSQL Logs
        if: ${{ always() }}
        run: |
          docker cp jepsen-control:/jepsen/jepsen-causal-consistency/store $GITHUB_WORKSPACE
          docker logs electric &> $GITHUB_WORKSPACE/store/current/electricsql.log 
          docker logs postgres &> $GITHUB_WORKSPACE/store/current/postgresql.log 
          tail -n 100 $GITHUB_WORKSPACE/store/current/jepsen.log > $GITHUB_WORKSPACE/store/current/tail-jepsen.log

      - name: 'Jepsen Test Artifacts: summary'
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.test-title }}-summary'
          path: |
            ${{ github.workspace }}/store/current/results.edn
            ${{ github.workspace }}/store/current/tail-jepsen.log
            
      - name: 'Jepsen Test Artifacts: failure-full'
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.test-title }}-failure-full'
          path: |
            ${{ github.workspace }}/store/current
