name: sql-txns - Causal Matrix

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  sql-txns-causal:
    uses: nurturenature/jepsen-causal-consistency/.github/workflows/run-jepsen-tests.yml@main
    with:
      workloads: >
        [ 'better-sqlite', 'pgexec-pglite' ]
      nemeses: >
        [ 'none' ]
      rates: >
        [ '5', '10', '15' ]
      time-limits: >
        ['60', '180', '300' ]
