name: 'TypeScript API and Homogeneous Transactions'

on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Name of Test'
        type: string
        required: true
        default: 'TypeScript API and Homogeneous Transactions'
      jepsen_cli:
        description: 'Jepsen CLI'
        type: string
        required: true
        default: 'lein run test --workload lww-homogeneous --electricsql-nodes n1,n2,n3,n4,n5 --rate 50 --time-limit 100'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  typescript-api-and-homogeneous-transactions:
    uses: nurturenature/jepsen-causal-consistency/.github/workflows/ad-hoc-jepsen-test.yml@main
    with:
      test_name: ${{ inputs.test_name || 'TypeScript API and Homogeneous Transactions' }}
      jepsen_cli: ${{ inputs.jepsen_cli || 'lein run test --workload lww-homogeneous --electricsql-nodes n1,n2,n3,n4,n5 --rate 50 --time-limit 100' }}
